function [q,posteriors] = ExpectationStep(...
    n_clusters,...
    samples_X,...
    means,...
    sigma,...
    priors...
)
% estimate likelihoods - given parameters
    for cluster_idx=1:n_clusters
        sigma(:,:,cluster_idx)=sigma(:,:,cluster_idx)+eye(5)*.001;% keep psd
        likelihoods(:,cluster_idx) = mvnpdf(samples_X,...
            means(cluster_idx,:),...
            sigma(:,:,cluster_idx));
    end
% estimate join and posterior
    joint = likelihoods .* priors;
    posteriors =joint./sum(joint,2);% soft cluster
    % this prevents -inf error
    joint(joint == 0) = 1e-100;
    log_joint = log(joint);
    q = sum(sum(posteriors.*log_joint));
end

